openapi: 3.0.3
info:
  title: Serving static files from embed.FS via HTTP
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /public/{filename}:
    get:
      tags:
      - asset
      summary: public asset
      operationId: asset#public
      parameters:
      - name: filename
        in: path
        description: Path to downloaded file.
        required: true
        schema:
          type: string
          description: Path to downloaded file.
          example: Aliquam fugit et saepe quibusdam unde culpa.
        example: Sint voluptatem molestiae.
      responses:
        "200":
          description: ""
          headers:
            Content-Length:
              description: Length is the downloaded content length in bytes.
              required: true
              schema:
                type: integer
                description: Length is the downloaded content length in bytes.
                example: 4194304
                format: int64
              example: 4194304
            Content-Type:
              description: Content-Type is the content type of the downloaded file.
              schema:
                type: string
                description: Content-Type is the content type of the downloaded file.
                example: application/json
              example: application/json
          content:
            application/json:
              example: {}
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      description: Could not locate file for download
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
